### ISSUE TITLE
LFXSocketUDP leak

### ISSUE THREAD

**Issue by darkrift** [LIFX/lifx-sdk-android#26]
There is a leak in the LFXSocketUPD class. As it is run in a thread, it opens a local DatagramSocket but that socket is never closed after the message is sent.

What happens then is that all the available system UDP sockets can potentially be opened locally. As they are not referenced, I suspect they are closed by the garbage collection.

I believe the .setReuseAddress(true) call was to reduce this kind of problem, however, the no-arg constructor bind the DatagramSocket to the magic port 0 which bind it to any available port so I believe the reuseAddress doesn't do anything here.

I don't know much about the lifx protocol, but another improvment could be to put the opening statement of the socket outside of the loop (according that multiple message can be sent on the same socket). Also, the datagram sending socket should either be closed at the end of the process, or keep the very first available port that was taken when opening the first socket (through getPort()), keep it in a class variable locally and reuse it so that reuseAddress works better. Also, when isClosed() returns false, another attempt to open a local UDP socket could be made.

With all those fixes, at best a single UDP socket would be created, at worst N where N is the number of messages, and the opened socket would all be closed at the end of the method (or socket itself could be kept in a local class variable).

**Comment by Cakey123445** [comment]
Agree with you that .setReuseAddress(true) would seem to be pointless for a transmit socket that is allocated randomly.

The creation of a socket for each message might intentional though, its hard to tell. If the messaging system guarantees each message is smaller than the smallest guaranteed datagram (576) then each received packet can be taken as a whole message/command. If they can be larger than 576 then the source address could be used to re-assemble. Its hard to see that a tx message to a LIFX would be larger than 576 but no way to tell so I'll leave the socket per message but will add the close on each socket just to be safe.

**Comment by smarthall** [comment]
Thanks for the fix @Cakey123445!
